sudo: required
services:
  - docker

before_install:
  - docker build -t qha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true qha/docker-react npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "us-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-335716680414"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
